version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10-browsers

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}

      - run: npm run download-pages

      - run: npm run prerender

      - run: npm run generate-sitemap

      - run: cp ./public/ads.txt ./dist/browser/ads.txt

      - deploy:
          name: Deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "prerender" ]; then
              npx netlify-cli deploy --dir=dist/browser
            fi
